### ISSUE TITLE
New shop checkout flow

### ISSUE THREAD

**Issue by sergei-maertens** [modelbrouwers/modelbrouwers#84]
I took a look at the existing checkout and drafted the checkout flow for the new shop. It's not that different, and I'm open to suggestions to make it better of course.

## Entry

There's two ways to enter it:

* from the small cart inset on the top right, with the checkout button
* from the card detail page, which should have two prominent buttons: `continue shopping` and `checkout`

![image](https://user-images.githubusercontent.com/5518550/57193773-296ad200-6f3f-11e9-9ef6-3090d6f11289.png)

## Account details

Most of this applies if the user is not logged in. If the user is already logged in, this step can be skipped entirely.

* Most prominent button should be to `Continue without account`. This means the user has to fill in all fields, but don't have to sign up or sign in

* Below that, the sign up and sign in buttons. Each button should just redirect to the respective, existing page, and after login/sign-up, redirect you back to the checkout process. When signing up, we should tweak the sign up a bit. A confirmation link to activate your account shouldn't be needed - instead, as soon as a payment is received, the account should be activated. We can still send out the e-mail to activate so they can use the rest of the site immediately. Signup flow etc. can be left for me, I don't want to distract from the actual shop flow.

![image](https://user-images.githubusercontent.com/5518550/57193785-53bc8f80-6f3f-11e9-80a6-682841cd3268.png)

Signing in/up does nothing more than pre-filling data we know already so that you can progress through the checkout faster. We can also apply reductions if they're configured on your account.

## Address details

Pre-fill if possible, of course, but all data should be editable.

All field should be editable, after pre-filling. We also ask for optional company/KVK fields (KVKV = Chamber of Commerce) for companies buying stuff. Not sure if that happens often.

The old form had the province required, but I'm not sure if that's really needed.

**Filling in the shipping address here should also kick off the calculation for shipping costs**

![image](https://user-images.githubusercontent.com/5518550/57193826-dfceb700-6f3f-11e9-948d-19146c7321cb.png)

## Payment

Payment step - make it a bit more graphical. We want the name of the payment option accompanied with an easily-identifiable logo. After selecting the payment option, any possible payment specific options should display. Below the options, or besides, if it's a visually hindering? E.g. for iDeal you need to select your bank afterwards.

A summary of the cart + shipping costs should be shown here again actually (not in the sketch) so that it's clear how much you're paying.

Above the payment button, there needs to be an 'I agree with the T&S blabla' button, initially unchecked, must be checked to proceed.

![image](https://user-images.githubusercontent.com/5518550/57193882-74d1b000-6f40-11e9-970c-b5df82337960.png)

## Confirmation

If all is well, a confirmation page with order reference is shown. Also, an e-mail should be send with the details and any possible instructions (such as payment instructions by bank transfer).

![image](https://user-images.githubusercontent.com/5518550/57193928-deea5500-6f40-11e9-8e5e-587898d3646c.png)

**Comment by Clarity-89** [comment]
Looks good so far. Another option could be to have steps 1-3 on the same page if there's not too much info, smth like this: 
![checkout](https://user-images.githubusercontent.com/8878045/57194513-6b504400-6f50-11e9-9ffb-499e0769f5ef.png)

**Comment by sergei-maertens** [comment]
I find putting it all together quite a visual overload, no?

**Comment by Clarity-89** [comment]
Could be if there's too many steps. Maybe step-based approach is better in this case.

I was thinking maybe it'd be better to combine steps 1 and 2, like show a contact form and below that sign up/sign in buttons in some kind of unobtrusive way. That way we can skip "continue without signup" button and keep the checkout a bit more simple. Not sure how important it is that user is signed up tho.

**Comment by sergei-maertens** [comment]
Fixed via #144
